language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
  - nightly

before_script:
 - npm install -g bower
 - composer install

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly

script: bin/phpunit -c app
